[package]
name = "fuzz-targets"
version = "0.0.1"
publish = false
edition = "2018"

[lib]
path = "mod.rs"

[dependencies]
anyhow = "1.0"
byteorder = "1"
tikv_util = { path = "../../components/tikv_util", default-features = false }
