[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = ["engine/protobuf-codec"]
prost-codec = ["engine/prost-codec"]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
failpoints = ["fail/failpoints"]

[dependencies]
engine = { path = "../engine" }
engine_traits = { path = "../engine_traits" }
num_cpus = "1"
prometheus = { version = "0.8", features = ["nightly", "push"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
lazy_static = "1.4.0"
log_wrappers = { path = "../log_wrappers" }
time = "0.1"
configuration = { path = "../configuration" }
serde = "1.0"
serde_derive = "1.0"
coarsetime = "0.1"
fail = "0.4"

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"
branch = "tikv-4.x"

[dev-dependencies]
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-4.0", default-features = false }
tempfile = "3.0"
rand = "0.7"
toml = "0.4"
